# Generated by Django 2.2.2 on 2019-12-11 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('Likes', models.IntegerField()),
                ('Content', models.TextField()),
                ('Posted Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('Likes', models.IntegerField()),
                ('Content', models.TextField()),
                ('Posted Date', models.DateTimeField(auto_now=True)),
                ('Title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nested_Reply',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('Likes', models.IntegerField()),
                ('Content', models.TextField()),
                ('Posted Date', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Nested_Reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment_Reply',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('Likes', models.IntegerField()),
                ('Content', models.TextField()),
                ('Posted Date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
